//! Cross-impl resolution constants, generated by build.rs from the shared
//! bench/parity/resolution_constants.yaml. Drift is a build error (see build.rs).
include!(concat!(env!("OUT_DIR"), "/parity_constants_gen.rs"));
